name: minerva
description: Server side framework for Dart. Allows you to create multithreaded REST API.
version: 0.1.8
homepage: https://github.com/GlebBatykov/minerva

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  path: ^1.8.2
  intl: ^0.17.0
  args: ^2.3.1
  mime: ^1.0.2
  crypt: ^4.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  minerva: minerva
