name: minerva
description: Dart backend framework. Supports multithreading, websockets. It contains a project build system, a request processing pipeline, authentication aids, and logging tools.
version: 0.2.0
homepage: https://github.com/GlebBatykov/minerva

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  path: ^1.8.2
  intl: ^0.17.0
  args: ^2.3.1
  mime: ^1.0.2
  crypt: ^4.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  minerva: minerva
